import "./globals.css";

import { ThemeProvider } from "@/utils/ThemeProvider";
import ThemeSidebar from "@/components/ThemeSidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Ebinesh Rabin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
    {/* <html lang="en"> */}
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={"antialiased"}>
        <ThemeProvider>
          {children}
          <ThemeSidebar />
          <Toaster position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
